# This file is machine-generated - editing it directly is not advised

[[TERMIOS]]
git-tree-sha1 = "b34071a98b5bdb92ce7694071c7b3dee9464c964"
uuid = "10233e3b-0d6c-416a-8c1a-d3d286bd6cd2"
version = "0.2.1"
