name = "KeyboardDriven"
uuid = "d6b73c45-a735-4b19-932b-179aebda8fdc"
authors = ["Stefan Peterson <stefan.j.peterson@gmail.com>"]
version = "0.1.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
TERMIOS = "10233e3b-0d6c-416a-8c1a-d3d286bd6cd2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1"
